export const config ={
    "webSiteTag":"dafa",
    "gameTag":"dafa",
    "apiPath": "/api/v0/",
    "version": "1.0.0",
    "promotionUrl": "/_promotion/web/index.html",
    "spec":"dafa-bt6",
    "appName":"Dafabet",
    "title":"dafabet在线投注亚洲最好的在线投注网站",
    "agentLoginUrl":"https://ag.betcn.app",
    "email":"xp9677@gmail.com",
    "skype":"",
    "qq":"",
    "phone":"",
    "weixin":"",
    "timezone": "美东时间",
    "prdImgUrl":"",
    "isApp":false,
    "IsLDL":false,
    "api":"asldkj"
}
